import{bytes,orderDevices,stale}from './format.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),embed=params.get('embed')==='1';
if(embed)document.body.classList.add('embed');
let router='',routers=[],meta=null,report=null,lastLive=null,busy=false,reportAt=0,generation=0;
const text=(id,v)=>{$(id).textContent=v},showError=e=>{text('error',e.message||String(e));$('error').hidden=false};
async function request(path,options={}){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',...options});const d=await r.json();if(!r.ok)throw new Error(d.error||`请求失败 (${r.status})`);return d}
const endpoint=action=>`/api/traffic-extension/${action}?router=${encodeURIComponent(router)}`;
function status(id,h,configured,threshold){const good=configured&&!h.error&&!stale(h.lastAt,Date.now(),threshold);text(id,!configured?'未配置':h.error?'采集异常':good?'● 正在采集':'等待采样 / 已过期');$(id).classList.toggle('online',good);$(id).title=h.error||''}
function draw(id,rows,rate=false){const c=$(id),ctx=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);if(!w||!h)return;const muted=getComputedStyle(document.documentElement).getPropertyValue('--muted').trim(),line=getComputedStyle(document.documentElement).getPropertyValue('--line').trim();const left=68,right=w-10,top=12,bottom=h-22;const max=Math.max(1,...rows.flatMap(x=>[x.download,x.upload]));ctx.font='10px system-ui';ctx.fillStyle=muted;ctx.strokeStyle=line;for(let i=0;i<3;i++){const y=top+(bottom-top)*i/2;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillText(bytes(max*(1-i/2))+(rate?'/s':''),0,y+4)}if(rows.length<2)return;const first=rows[0].at,last=rows.at(-1).at;for(const[key,color]of[['download','#276ef1'],['upload','#0aa879']]){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();rows.forEach((x,i)=>{const xx=left+(right-left)*(x.at-first)/(last-first||1),y=bottom-(bottom-top)*x[key]/max;if(!i||x.at-rows[i-1].at>(rate?5000:3700000))ctx.moveTo(xx,y);else ctx.lineTo(xx,y)});ctx.stroke()}ctx.fillStyle=muted;const fmt=x=>new Date(x).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Shanghai'});ctx.fillText(fmt(first),left,h-3);ctx.textAlign='right';ctx.fillText(fmt(last),right,h-3)}
function live(d){lastLive=d;const v=d.live;status('clash-status',v.clash,d.enabled&&d.hasClash,6000);status('ros-status',v.ros,d.enabled&&d.hasROS,45000);const fresh=d.enabled&&!v.clash.error&&!stale(v.clash.lastAt,Date.now(),6000);text('down-rate',fresh?bytes(v.down)+'/s':'—');text('up-rate',fresh?bytes(v.up)+'/s':'—');text('core-down',v.clash.lastAt?bytes(v.download):'—');text('core-up',v.clash.lastAt?bytes(v.upload):'—');text('connections',fresh?`${v.clash.count} 个连接`:'');$('chart-empty').hidden=(v.rates||[]).length>1;draw('live-chart',(v.rates||[]).map(x=>({at:x.at,download:x.down,upload:x.up})),true)}
function table(id,rows){const body=$(id);body.replaceChildren();if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.className='empty';td.textContent=id==='devices'?'暂无设备数据，请检查 Kid Control 统计和连接设置':'未指定基础设施，或尚未采集到对应设备';tr.append(td);body.append(tr);return}orderDevices(rows,$('sort').value).forEach((r,i)=>{const tr=document.createElement('tr');const vals=[String(i+1),r.name||'未命名设备',r.mac,bytes(r.download),bytes(r.upload),bytes(r.download+r.upload)];vals.forEach((value,j)=>{const td=document.createElement('td');td.textContent=value;if(j===1){const small=document.createElement('small');small.textContent=(r.ip||'IP 暂未知')+(stale(r.lastAt,Date.now(),60000)?' · 最近未采集':'');td.append(small)}tr.append(td)});tr.title=`首次接入已有下载 ${bytes(r.baselineDownload)} / 上传 ${bytes(r.baselineUpload)}（未计入周期）\nROS 当前计数：下载 ${bytes(r.currentDownload)} / 上传 ${bytes(r.currentUpload)}`;body.append(tr)})}
function history(d){report=d;text('history-down',bytes(d.download));text('history-up',bytes(d.upload));text('recorded-since',d.firstAt?'开始采集：'+new Date(d.firstAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'尚未采集到数据');text('coverage',`已有计数不归入今日；统计开始前及断连期间的流量不补算。${d.gaps?`所选周期有 ${d.gaps} 条来源/设备采集缺口或重置记录，当前累计不完整。`:'所选周期暂无已记录的采集缺口（不代表接入前有历史）。'} 跨分钟按时间比例分配。`);draw('history-chart',d.clash);table('devices',d.devices.filter(x=>!x.infrastructure));table('infrastructure',d.devices.filter(x=>x.infrastructure))}
function clearView(){report=null;lastLive=null;for(const id of ['down-rate','up-rate','core-down','core-up','history-down','history-up'])text(id,'—');table('devices',[]);table('infrastructure',[]);draw('live-chart',[]);draw('history-chart',[])}
async function update(force=false){if(busy||!router||document.hidden)return;busy=true;const g=generation;try{$('error').hidden=true;const l=await request(endpoint('live'));if(g!==generation)return;live(l);if(!embed&&(force||Date.now()-reportAt>15000)){if(meta.history?.includes(router)){const q=new URLSearchParams({period:$('period').value,from:$('from').value,to:$('to').value});const h=await request(endpoint('report')+'&'+q);if(g!==generation)return;history(h);reportAt=Date.now()}else{text('coverage','当前账号没有此路由器的历史统计权限。')}}}catch(e){if(g===generation){showError(e);if(lastLive)live({...lastLive,enabled:false})}}finally{busy=false}}
function selectRouter(id){generation++;router=id;reportAt=0;clearView();$('settings').hidden=!(meta?.manageSettings&&meta?.manageable?.includes(router));$('details').href='/extensions/traffic/?router='+encodeURIComponent(router);void update(true)}
$('router').addEventListener('change',()=>selectRouter($('router').value));$('period').addEventListener('change',()=>{$('dates').hidden=$('period').value!=='custom';reportAt=0;void update(true)});for(const id of ['from','to'])$(id).addEventListener('change',()=>{reportAt=0;void update(true)});$('refresh').addEventListener('click',()=>void update(true));$('sort').addEventListener('change',()=>{if(report)history(report)});
$('settings').addEventListener('click',async()=>{try{const g=generation,d=await request(endpoint('config'));if(g!==generation)return;const c=d.config,base=routers.find(r=>r.id===router)||{};$('enabled').checked=c.enabled;$('clash-url').value=c.clashURL||'';$('clash-secret').value='';$('clash-secret').placeholder=d.hasClashSecret?'已保存；留空保留':'未配置';$('ros-host').value=c.ros.host||base.host||'';$('ros-port').value=c.ros.host?c.ros.port:(base.port||8728);$('ros-user').value=c.ros.username||base.username||'';$('ros-password').value='';$('ros-password').placeholder=d.hasROSPassword?'已保存；留空保留':'单独输入统计账号密码';$('ros-tls').checked=c.ros.host?c.ros.tls:Boolean(base.tls);$('ros-insecure').checked=c.ros.insecureTLS;$('infra').value=(c.infrastructure||[]).join('\n');$('clear-clash-secret').checked=false;$('clear-ros-password').checked=false;$('save-error').hidden=true;$('config-dialog').showModal()}catch(e){showError(e)}});
$('close-settings').addEventListener('click',()=>$('config-dialog').close());$('config-form').addEventListener('submit',async e=>{e.preventDefault();$('save').disabled=true;$('save-error').hidden=true;try{const config={routerId:router,enabled:$('enabled').checked,clashURL:$('clash-url').value.trim(),clashSecret:$('clash-secret').value,ros:{host:$('ros-host').value.trim(),port:Number($('ros-port').value),username:$('ros-user').value.trim(),password:$('ros-password').value,tls:$('ros-tls').checked,insecureTLS:$('ros-insecure').checked},infrastructure:$('infra').value.split('\n').map(x=>x.trim()).filter(Boolean)};await request(endpoint('config'),{method:'POST',headers:{'Content-Type':'application/json','X-Traffic-Extension':'1'},body:JSON.stringify({config,clearClashSecret:$('clear-clash-secret').checked,clearROSPassword:$('clear-ros-password').checked})});$('clash-secret').value='';$('ros-password').value='';$('config-dialog').close();reportAt=0;await update(true)}catch(e){text('save-error',e.message);$('save-error').hidden=false}finally{$('save').disabled=false}});
new ResizeObserver(()=>{if(lastLive)live(lastLive);if(report&&!embed)draw('history-chart',report.clash)}).observe($('live-chart').parentElement);
try{meta=await request('/api/traffic-extension/meta');const r=await request('/api/routers');routers=(r.routers||[]).filter(x=>meta.readable?.includes(x.id));for(const x of routers){const o=document.createElement('option');o.value=x.id;o.textContent=x.label||x.host||x.id;$('router').append(o)}const wanted=params.get('router')||r.activeId||routers[0]?.id;$('router').value=routers.some(x=>x.id===wanted)?wanted:(routers[0]?.id||'');const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});$('from').value=today;$('to').value=today;selectRouter($('router').value);if(!router)showError(new Error('请先在 MikroDash 添加路由器，或检查查看权限。'))}catch(e){showError(e)}
setInterval(()=>void update(),2000);
